# Gitleaks configuration for Bubble Timer project
# This file configures what secrets to detect and what to ignore

[global]
# Global settings
verbose = false
redact = true
debug = false

# Custom rules for Bubble Timer specific patterns
[[rules]]
id = "bubble-timer-custom"
description = "Custom rules for Bubble Timer project"
regex = '''(?i)(api_key|secret_key|access_key|private_key|password|token|credential)['"]?\s*[:=]\s*['"]?[a-zA-Z0-9\-_]{20,}['"]?'''
tags = ["key", "Bubble Timer"]

# Ignore Firebase public API keys (these are safe to commit)
[[rules]]
id = "firebase-api-key"
description = "Firebase API keys (public, safe to commit)"
regex = '''AIza[0-9A-Za-z\-_]{35}'''
tags = ["key", "Firebase"]
allowlist = [
    "google-services.json",
    "firebase",
    "firebase config"
]

# Ignore AWS API Gateway URLs (public endpoints)
[[rules]]
id = "aws-api-gateway-url"
description = "AWS API Gateway URLs (public endpoints)"
regex = '''https://[a-zA-Z0-9\-_]+\.execute-api\.[a-zA-Z0-9\-_]+\.amazonaws\.com'''
tags = ["AWS", "API Gateway"]
allowlist = [
    "execute-api.us-east-1.amazonaws.com",
    "api gateway",
    "endpoint"
]

# Ignore test data and mock credentials
[[rules]]
id = "test-credentials"
description = "Test and mock credentials"
regex = '''(?i)(test|mock|example|sample|dummy|fake)_(key|token|password|secret)['"]?\s*[:=]\s*['"]?[a-zA-Z0-9\-_]+['"]?'''
tags = ["test", "mock"]
allowlist = [
    "test",
    "mock",
    "example",
    "sample"
]

# Ignore documentation examples
[[rules]]
id = "documentation-examples"
description = "Documentation examples with placeholder values"
regex = '''(?i)(your_|placeholder_|example_)(key|token|password|secret)['"]?\s*[:=]\s*['"]?[a-zA-Z0-9\-_]+['"]?'''
tags = ["documentation", "example"]
allowlist = [
    "docs",
    "documentation",
    "example",
    "placeholder"
]

# Standard secret patterns to detect
[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["key", "AWS"]

[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''ghp_[a-zA-Z0-9]{36}'''
tags = ["key", "GitHub"]

[[rules]]
id = "github-oauth-token"
description = "GitHub OAuth Token"
regex = '''gho_[a-zA-Z0-9]{36}'''
tags = ["key", "GitHub"]

[[rules]]
id = "github-user-to-server-token"
description = "GitHub User-to-Server Token"
regex = '''ghu_[a-zA-Z0-9]{36}'''
tags = ["key", "GitHub"]

[[rules]]
id = "github-server-to-server-token"
description = "GitHub Server-to-Server Token"
regex = '''ghs_[a-zA-Z0-9]{36}'''
tags = ["key", "GitHub"]

[[rules]]
id = "github-refresh-token"
description = "GitHub Refresh Token"
regex = '''ghr_[a-zA-Z0-9]{36}'''
tags = ["key", "GitHub"]

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN PRIVATE KEY-----'''
tags = ["key", "Private Key"]

[[rules]]
id = "rsa-private-key"
description = "RSA Private Key"
regex = '''-----BEGIN RSA PRIVATE KEY-----'''
tags = ["key", "RSA Private Key"]

[[rules]]
id = "database-url"
description = "Database URL with credentials"
regex = '''(mysql|postgresql|mongodb)://[a-zA-Z0-9\-_]+:[a-zA-Z0-9\-_]+@[a-zA-Z0-9\-_.]+:[0-9]+/[a-zA-Z0-9\-_]+'''
tags = ["key", "Database"]

# Allowlist patterns for known safe files
[allowlist]
description = "Allowlist for known safe files and patterns"
files = [
    "google-services.json",
    "SECURITY.md",
    "README.md",
    "*.md",
    "*.txt",
    "*.toml",
    "*.yml",
    "*.yaml"
]

# Allowlist for specific patterns
[[allowlist.rules]]
description = "Firebase configuration files"
regex = '''google-services\.json'''

[[allowlist.rules]]
description = "Documentation files"
regex = '''\.md$'''

[[allowlist.rules]]
description = "Configuration files"
regex = '''\.(toml|yml|yaml)$'''

[[allowlist.rules]]
description = "Test files"
regex = '''test|spec|mock|example'''

[[allowlist.rules]]
description = "Public API endpoints"
regex = '''execute-api\.us-east-1\.amazonaws\.com'''
